### ISSUE TITLE
ENCRYPTABLES SHARING: File db:migration

### ISSUE THREAD

**Issue by njaeggi** [puzzle-bbt/bbt#104]
For file sharing and later also for credential share we need 2 new attributes in encryptables table. 

### Conception
- https://codimd.puzzle.ch/tozsq7r-STCJ29iqsMbS9w#

| Name   |      Type      | 
|----------|:-------------:|
| transfer_password |  binary | 
| receiver_id |    integer   |   

This migration already exists: https://github.com/puzzle/cryptopus/blob/encryptables-sharing-560/db/migrate/20220506091924_add_transfer_password_to_encryptables.rb

**Comment by lkleisa** [comment]
[Migration](https://github.com/puzzle/cryptopus/blob/encryptables-sharing-560/db/migrate/20220506091924_add_transfer_password_to_encryptables.rb) is on branch [encryptables-sharing-560](https://github.com/puzzle/cryptopus/tree/encryptables-sharing-560). Move issue to implemented because migration resolves issue, but didn't add PR, because we can keep this branch for [secure file sharing issue](https://github.com/puzzle/cryptopus/issues/561)
